language: csharp
solution: YoutubeQueuer/YoutubeQueuer.sln
install:
  - nuget restore YoutubeQueuer/YoutubeQueuer.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release YoutubeQueuer/YoutubeQueuer.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./YoutubeQueuer/YoutubeQueuer.Tests/bin/Release/YoutubeQueuer.Tests.dll
