language: csharp
before_script:
  - npm install -g jasmine
solution: YoutubeQueuer/YoutubeQueuer.sln
node_js: "4"
install:
  - nuget restore YoutubeQueuer/YoutubeQueuer.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
  - cd YoutubeQueuerJS && npm install && cd ..
script:
  - xbuild /p:Configuration=Release YoutubeQueuer/YoutubeQueuer.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./YoutubeQueuer/YoutubeQueuer.Tests/bin/Release/YoutubeQueuer.Tests.dll
  - cd YoutubeQueuerJS && jasmine && cd ..