language: csharp
solution: YoutubeQueuer/YoutubeQueuer.sln
install:
  - nuget restore YoutubeQueuer/YoutubeQueuer.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release YoutubeQueuer/YoutubeQueuer.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./YoutubeQueuer/YoutubeQueuer.Tests/bin/Release/YoutubeQueuer.Tests.dll
